name: ohanap
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  
  country_flags: ^2.2.0
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  iconsax: ^0.0.8
  shared_preferences: ^2.0.13

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/